### ISSUE TITLE
Logger error

### ISSUE THREAD

**Issue by andrewjmc** [statisticalbiotechnology/quandenser#14]
Latest rerun gave unusual error from dinosaur regarding logging.

```
java -Xmx48G -jar "C:\Program Files\quandenser-v0-02\share\java/Dinosaur-1.1.3.free.jar" --force  --profiling=true --nReport=0  --concurrency=11 --seed=1 --outDir=.\quandenser_output_only_samples_noOX1\percolator/search_and_link_202_to_102.psms.pout_dinosaur --advParams="C:\Program Files\quandenser-v0-02\share\java/advParams_dinosaur_targeted.txt" --mode=target --targets=.\quandenser_output_only_samples_noOX1\percolator/search_and_link_202_to_102.psms.pout.dinosaur_targets.tsv E:\RAW\Lab1\Pilot_2\FL948_MSQ1388_20180605_SM_145.mzML
Dinosaur 1.1.3    built:${maven.build.timestamp}
  mzML file: E:\RAW\Lab1\Pilot_2\FL948_MSQ1388_20180605_SM_145.mzML
    out dir: .\quandenser_output_only_samples_noOX1\percolator/search_and_link_202_to_102.psms.pout_dinosaur
   out name: FL948_MSQ1388_20180605_SM_145

[WARN] [01/18/2020 02:50:24.301] [main] [EventStream(akka://actor-system)] Logger log1-Logging$DefaultLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:116)
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:115)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Failure.recover(Try.scala:185)
        at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
        at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:110)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
        at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:110)
        at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
        at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:619)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:616)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:616)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:633)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
        at se.lth.immun.FeatureFinder.<init>(FeatureFinder.scala:37)
        at se.lth.immun.Dinosaur$.main(Dinosaur.scala:60)
        at se.lth.immun.Dinosaur.main(Dinosaur.scala)
Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
        at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:185)
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:114)
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:113)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
        ... 19 more
Exception in thread "main" akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.Logging$DefaultLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Logging$DefaultLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
        at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:144)
        at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
        at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:619)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:616)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:616)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:633)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:109)
        at se.lth.immun.FeatureFinder.<init>(FeatureFinder.scala:37)
        at se.lth.immun.Dinosaur$.main(Dinosaur.scala:60)
        at se.lth.immun.Dinosaur.main(Dinosaur.scala)
Exception caught: Dinosaur failed with exit code 1. Terminating..
```

This happened after 245 links. I've checked there's no issue with disk space.

I can find a report from akka logging regarging the timeout errors, but looks like it was a problem with the person's own code (https://github.com/akka/akka/issues/15675).

I suspect this is more likely to be a problem with dinosaur. If you agree, I will raise it on the dinosaur  page.

**Comment by MatthewThe** [comment]
I haven't seen that error message before, but most likely it's indeed a problem with Dinosaur itself. Is there anything strange with the input file? And is it possible to just rerun the Dinosaur command?

**Comment by andrewjmc** [comment]
The command alone seems to run fine. The error occurred about 11 hours into the percolator steps. I wondered if it could be a power setting, but the machine is set never to sleep.

I'm rerunning the whole batch with the interim output, hoping the linkages will be deterministic and therefore reuse the existing link files.

Maybe it was just a sporadic error because the machine became busy (Windows 10 decided to do something more important!) and the timeout was hit.

**Comment by andrewjmc** [comment]
Rerun has picked up where it left off fine. I'll close the issue.
