### ISSUE TITLE
Issue running Example

### ISSUE THREAD

**Issue by Alexander-Sol** [statisticalbiotechnology/quandenser#25]
I'm trying to run the example you've uploaded, but I encountered some difficulties running Triqler. Specifically, line 1 of the Triqler.sh script is throwing an error

I'm running Windows 11 with Crux v4.2.

I've included the error message below.

`Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\triqler\convert\quandenser.py", line 232, in <module>
    main()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\triqler\convert\quandenser.py", line 38, in main
    convertQuandenserToTriqler(
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\triqler\convert\quandenser.py", line 142, in convertQuandenserToTriqler
    specToPeptideMap = helpers.parsePsmsPoutFiles(psmsOutputFiles)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\triqler\convert\helpers.py", line 40, in parsePsmsPoutFiles
    for psm in percolator.parsePsmsPout(psmsOutputFile):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\triqler\convert\percolator.py", line 95, in parsePsmsPout
    float(row[1]),
ValueError: could not convert string to float: './Quandenser_output/consensus_spectra/MaRaCluster.consensus.part1.ms2'`

**Comment by MatthewThe** [comment]
I suspect that the problem is that Crux changed its output format, could you post the first 5 lines of `crux_output/percolator.target.psms.txt`

**Comment by Alexander-Sol** [comment]
> PSMId	filename	score	q-value	posterior_error_prob	peptide	proteinIds
target_0_1681601_4_1	./Quandenser_output/consensus_spectra/MaRaCluster.consensus.part1.ms2	3.36331	0.000339213	6.11202e-11	K.RGWGQLTSNLLLIGMEGNVTPAHYDEQQNFFAQIK.G	HPRR4280170_poolB
target_0_1609101_3_1	./Quandenser_output/consensus_spectra/MaRaCluster.consensus.part1.ms2	3.17684	0.000339213	2.04056e-10	K.KADCPIAWANLMLFDYKDQLK.T	HPRR4040265_poolB
target_0_1764801_3_1	./Quandenser_output/consensus_spectra/MaRaCluster.consensus.part1.ms2	3.02753	0.000339213	5.35748e-10	R.FPGNLLLNPFGISITSQSLNPGPFRTPK.A	HPRR4030528_poolB
target_0_1726301_3_1	./Quandenser_output/consensus_spectra/MaRaCluster.consensus.part1.ms2	2.99247	0.000339213	6.72044e-10	R.ATTNIIQPLLHAQWVLGDWSECSSTCGAGWQR.R	HPRR2700128_poolA

**Comment by MatthewThe** [comment]
Yes, Crux indeed switched their output format in 4.2.
I created a fix in the Triqler repo, you can reinstall it from GitHub:

```
git clone https://github.com/statisticalbiotechnology/triqler.git
cd triqler
pip install .
```

I will release a patch version for Triqler if this works for you.

**Comment by Alexander-Sol** [comment]
Yes, that fixed the issue! Thanks a bunch
